# Generated by Django 5.0.6 on 2026-06-03 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenadores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rutina',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='rutina',
            old_name='fecha_actualizacion',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='rutina',
            name='entrenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to=settings.AUTH_USER_MODEL),
        ),
    ]
