# Generated by Django 5.0.6 on 2026-06-03 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrenador',
            options={'verbose_name': 'Entrenador', 'verbose_name_plural': 'Entrenadores'},
        ),
        migrations.AlterModelOptions(
            name='rutina',
            options={'verbose_name': 'Rutina', 'verbose_name_plural': 'Rutinas'},
        ),
        migrations.RemoveField(
            model_name='entrenador',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='entrenador',
            name='is_trainer',
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='entrenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='rutinas/'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='nivel',
            field=models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
