# Generated by Django 5.0.6 on 2026-06-03 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrenadores', '0002_rename_fecha_creacion_rutina_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='imagen',
        ),
    ]
