# Generated by Django 5.0.6 on 2026-06-03 22:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenadores', '0003_remove_rutina_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrenador',
            name='is_trainer',
            field=models.BooleanField(default=True),
        ),
    ]
